version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    networks: 
      - frontend_net
    depends_on:
      - flask
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8880:80
      - 443:443

  flask:
    container_name: flask
    build: ./flaskapp
    volumes: 
     - ./flaskapp:/usr/src/flaskapp
    networks: 
      - db_net
      - frontend_net
    depends_on: 
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    restart: always
    networks: 
      - db_net
    volumes:
      - db-volume:/var/lib/postgresql/data

networks: 
  db_net:
    driver: bridge
  frontend_net:
    driver: bridge

volumes:
  db-volume:
    external: true
